version: '3.8'

services:
  nginx-proxy:
    image: hassaan2024/flask-v1:nginx-proxy-v1
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - FLASK_SERVER_ADDR=flask-app:8000
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app
    command: /app/start.sh

  flask-app:
    image: hassaan2024/flask-v1:flask-app-v1
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '8000:8000'
    depends_on:
      - mariadb
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DATABASE=blog
      - MYSQL_PORT=3306  

  mariadb:
    image: hassaan2024/flask-v1:mariadb-v1
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=blog
      - MYSQL_PORT=3306  
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

